import type {
  CategoryId,
  Cocktail,
  Dish,
  DishIngredient,
  DishTag,
  Localized,
} from "@/lib/types";

const L = (en: string, ru: string): Localized => ({ en, ru });

const ing = (
  id: string,
  en: string,
  ru: string,
  image: string,
  grams: string,
): DishIngredient => ({
  id,
  name: L(en, ru),
  image,
  grams,
});

export const menuCategories: { id: CategoryId; label: Localized }[] = [
  { id: "starters", label: L("Starters", "Закуски") },
  { id: "raw", label: L("Raw", "Raw") },
  { id: "pasta", label: L("Pasta", "Паста") },
  { id: "mains", label: L("Mains", "Горячее") },
  { id: "seafood", label: L("Seafood", "Морепродукты") },
  { id: "sides", label: L("Sides", "Гарниры") },
  { id: "desserts", label: L("Desserts", "Десерты") },
  { id: "drinks", label: L("Drinks", "Напитки") },
];

export const menuFilters: { id: DishTag; label: Localized }[] = [
  { id: "vegetarian", label: L("Vegetarian", "Вегетарианское") },
  { id: "spicy", label: L("Spicy", "Острое") },
  { id: "chefs-choice", label: L("Chef’s Choice", "Выбор шефа") },
  { id: "signature", label: L("Signature", "Авторское") },
  { id: "seasonal", label: L("Seasonal", "Сезонное") },
];

const I = {
  pasta: "/images/dish-tagliolini.jpg",
  tartare: "/images/dish-tartare.jpg",
  burrata: "/images/dish-burrata.jpg",
  octopus: "/images/dish-octopus.jpg",
  dessert: "/images/dish-dessert.jpg",
  cocktail: "/images/cocktail-martini.jpg",
  bar: "/images/bar.jpg",
  kitchen: "/images/journal-kitchen.jpg",
  chef: "/images/chef.jpg",
  truffle: "/images/journal-truffle.jpg",
  room: "/images/room-1.jpg",
  salmon: "/images/menu/salmon.jpg",
  tuna: "/images/menu/tuna.jpg",
  lobster: "/images/dish-tagliolini.jpg",
  cacio: "/images/menu/cacio.jpg",
  duck: "/images/menu/duck.jpg",
  steak: "/images/menu/steak.jpg",
  chicken: "/images/menu/duck.jpg",
  scallops: "/images/menu/scallops.jpg",
  seabass: "/images/dish-octopus.jpg",
  fries: "/images/menu/fries.jpg",
  veg: "/images/menu/veg.jpg",
  salad: "/images/menu/salad.jpg",
  fig: "/images/dish-dessert.jpg",
  lemon: "/images/menu/lemon.jpg",
};

function gallery(...images: string[]) {
  return images;
}

function dish(partial: Dish): Dish {
  return partial;
}

export const dishes: Dish[] = [
  dish({
    id: "burrata",
    slug: "burrata",
    name: L("Burrata", "Буррата"),
    category: "starters",
    summary: L("Tomato · basil · olive oil", "Томат · базилик · оливковое масло"),
    description: L(
      "Warm burrata, roasted cherry tomato, basil oil, and a whisper of aged balsamic.",
      "Тёплая буррата, печёные черри, базиликовое масло и едва заметный выдержанный бальзамик.",
    ),
    price: "890 ₽",
    image: I.burrata,
    gallery: gallery(I.burrata, I.salad, I.kitchen, I.room),
    ingredients: [
      ing("burrata", "Burrata", "Буррата", I.burrata, "180 г"),
      ing("tomato", "Tomato", "Томат", I.veg, "80 г"),
      ing("basil", "Basil", "Базилик", I.salad, "4 г"),
      ing("oil", "Olive oil", "Оливковое масло", I.burrata, "12 мл"),
    ],
    allergens: [L("Milk", "Молоко")],
    pairing: { name: L("Italian Vermentino", "Итальянский верментино"), price: "890 ₽ / glass" },
    chefNote: L("Leave the cream intact. Cut at the table.", "Крем не трогать. Разрезается у стола."),
    tags: ["vegetarian", "signature"],
    featured: true,
    seasonal: false,
    chefChoice: false,
    emphasis: "lg",
    alt: L("Burrata with roasted tomatoes and basil oil", "Буррата с печёными томатами"),
  }),
  dish({
    id: "beef-tartare",
    slug: "beef-tartare",
    name: L("Beef Tartare", "Тартар из говядины"),
    category: "starters",
    summary: L("Beef tenderloin · parmesan · truffle", "Вырезка · пармезан · трюфель"),
    description: L(
      "Dry-aged beef, smoked yolk, pickled mustard seed. Cut, not minced — texture first.",
      "Выдержанная говядина, копчёный желток, маринованное горчичное семя. Нарезается, не рубится.",
    ),
    price: "1 490 ₽",
    image: I.tartare,
    gallery: gallery(I.tartare, I.steak, I.kitchen, I.chef, I.room),
    ingredients: [
      ing("beef", "Beef tenderloin", "Говяжья вырезка", I.tartare, "140 г"),
      ing("parmesan", "Parmesan", "Пармезан", I.burrata, "18 г"),
      ing("truffle", "Truffle", "Трюфель", I.truffle, "5 г"),
      ing("yolk", "Smoked yolk", "Копчёный желток", I.tartare, "18 г"),
    ],
    allergens: [L("Milk", "Молоко"), L("Egg", "Яйцо")],
    pairing: { name: L("Pinot Noir, Burgundy", "Пино нуар, Бургундия"), price: "1 200 ₽ / glass" },
    chefNote: L("Texture first. Everything else follows.", "Сначала текстура. Остальное — следом."),
    tags: ["signature", "chefs-choice"],
    featured: true,
    seasonal: false,
    chefChoice: true,
    emphasis: "xl",
    alt: L("Beef tartare with smoked yolk on a dark plate", "Тартар из говядины"),
  }),
  dish({
    id: "charred-octopus",
    slug: "charred-octopus",
    name: L("Charred Octopus", "Осьминог на углях"),
    category: "starters",
    summary: L("Octopus · smoked potato · herbs", "Осьминог · копчёный картофель · травы"),
    description: L(
      "Slow-braised, then finished over binchotan. Fennel, citrus ash, and a warm potato cream.",
      "Долгое томление и финиш на бинчётане. Фенхель, цитрусовый пепел и тёплый картофельный крем.",
    ),
    price: "1 590 ₽",
    image: I.octopus,
    gallery: gallery(I.octopus, I.scallops, I.kitchen, I.room, I.chef),
    ingredients: [
      ing("octopus", "Octopus", "Осьминог", I.octopus, "180 г"),
      ing("potato", "Smoked potato", "Копчёный картофель", I.fries, "90 г"),
      ing("herbs", "Herbs", "Травы", I.salad, "6 г"),
      ing("fennel", "Fennel", "Фенхель", I.veg, "40 г"),
    ],
    allergens: [L("Mollusc", "Моллюски")],
    pairing: { name: L("Albariño", "Альбариньо"), price: "980 ₽ / glass" },
    chefNote: L("Char for perfume, not for theatre.", "Уголь — для аромата, не для жеста."),
    tags: ["signature"],
    featured: true,
    seasonal: false,
    chefChoice: false,
    emphasis: "md",
    alt: L("Charred octopus with fennel and citrus", "Осьминог на углях"),
  }),
  dish({
    id: "salmon-crudo",
    slug: "salmon-crudo",
    name: L("Salmon Crudo", "Крудо из лосося"),
    category: "raw",
    summary: L("Salmon · citrus · chili oil", "Лосось · цитрус · масло чили"),
    description: L(
      "Sliced thin, dressed cold. Citrus first, chili only as a finish.",
      "Тонкий срез, холодная заправка. Сначала цитрус, чили — только финиш.",
    ),
    price: "1 190 ₽",
    image: I.salmon,
    gallery: gallery(I.salmon, I.seabass, I.kitchen),
    ingredients: [
      ing("salmon", "Salmon", "Лосось", I.salmon, "110 г"),
      ing("citrus", "Citrus", "Цитрус", I.lemon, "25 г"),
      ing("chili", "Chili oil", "Масло чили", I.veg, "8 мл"),
    ],
    allergens: [L("Fish", "Рыба")],
    pairing: { name: L("Champagne brut", "Шампанское brut"), price: "1 400 ₽ / glass" },
    chefNote: L("Cold fish, warm spice. Keep the cut wide.", "Холодная рыба, тёплая специя."),
    tags: ["spicy", "seasonal"],
    featured: false,
    seasonal: true,
    chefChoice: false,
    emphasis: "lg",
    alt: L("Salmon crudo with citrus and chili oil", "Крудо из лосося"),
  }),
  dish({
    id: "tuna-tartare",
    slug: "tuna-tartare",
    name: L("Tuna Tartare", "Тартар из тунца"),
    category: "raw",
    summary: L("Tuna · avocado · sesame", "Тунец · авокадо · кунжут"),
    description: L(
      "Hand-cut tuna, ripe avocado, toasted sesame. Quiet heat.",
      "Тунец ручной нарезки, спелый авокадо, жареный кунжут. Тихое тепло.",
    ),
    price: "1 290 ₽",
    image: I.tuna,
    gallery: gallery(I.tuna, I.salmon, I.kitchen),
    ingredients: [
      ing("tuna", "Tuna", "Тунец", I.tuna, "120 г"),
      ing("avocado", "Avocado", "Авокадо", I.salad, "50 г"),
      ing("sesame", "Sesame", "Кунжут", I.tuna, "4 г"),
    ],
    allergens: [L("Fish", "Рыба"), L("Sesame", "Кунжут")],
    pairing: { name: L("Sake, junmai", "Сакэ дзюнмай"), price: "790 ₽ / glass" },
    chefNote: L("No mince. The knife does the work.", "Без фарша. Работает нож."),
    tags: ["spicy"],
    featured: false,
    seasonal: false,
    chefChoice: false,
    emphasis: "sm",
    alt: L("Tuna tartare with avocado and sesame", "Тартар из тунца"),
  }),
  dish({
    id: "black-truffle-tagliolini",
    slug: "black-truffle-tagliolini",
    name: L("Black Truffle Tagliolini", "Тальолини с чёрным трюфелем"),
    category: "pasta",
    summary: L("Tagliolini · black truffle · parmesan", "Тальолини · чёрный трюфель · пармезан"),
    description: L(
      "Hand-cut tagliolini, aged Parmigiano, and winter black truffle — shaved tableside, never as a gesture, always as the point.",
      "Тальолини ручной работы, выдержанный пармезан и зимний чёрный трюфель — натирается у стола.",
    ),
    price: "1 690 ₽",
    image: I.pasta,
    gallery: gallery(I.pasta, I.truffle, I.kitchen, I.chef, I.room),
    ingredients: [
      ing("tagliolini", "Tagliolini", "Тальолини", I.pasta, "110 г"),
      ing("truffle", "Black truffle", "Чёрный трюфель", I.truffle, "12 г"),
      ing("parmesan", "Parmesan", "Пармезан", I.burrata, "25 г"),
      ing("butter", "Butter", "Масло", I.dessert, "20 г"),
      ing("herbs", "Herbs", "Травы", I.salad, "3 г"),
    ],
    allergens: [L("Gluten", "Глютен"), L("Milk", "Молоко"), L("Egg", "Яйцо")],
    pairing: { name: L("Italian Barbera", "Итальянская барбера"), price: "1 100 ₽ / glass" },
    chefNote: L("Texture first. Everything else follows.", "Сначала текстура. Остальное — следом."),
    tags: ["signature", "chefs-choice", "seasonal"],
    featured: true,
    seasonal: true,
    chefChoice: true,
    emphasis: "xl",
    alt: L("Black truffle tagliolini plated on dark ceramic", "Тальолини с чёрным трюфелем"),
  }),
  dish({
    id: "lobster-linguine",
    slug: "lobster-linguine",
    name: L("Lobster Linguine", "Лингвини с лобстером"),
    category: "pasta",
    summary: L("Lobster · tomato · chili", "Лобстер · томат · чили"),
    description: L(
      "Sweet lobster, a short tomato reduction, chili that stays in the background.",
      "Сладкий лобстер, короткая томатная редукция, чили остаётся на втором плане.",
    ),
    price: "2 290 ₽",
    image: I.lobster,
    gallery: gallery(I.lobster, I.pasta, I.kitchen),
    ingredients: [
      ing("lobster", "Lobster", "Лобстер", I.lobster, "140 г"),
      ing("tomato", "Tomato", "Томат", I.veg, "60 г"),
      ing("chili", "Chili", "Чили", I.veg, "4 г"),
      ing("linguine", "Linguine", "Лингвини", I.pasta, "110 г"),
    ],
    allergens: [L("Gluten", "Глютен"), L("Crustacean", "Ракообразные")],
    pairing: { name: L("Chardonnay, Chablis", "Шардоне, Шабли"), price: "1 250 ₽ / glass" },
    chefNote: L("The lobster should taste of itself.", "Лобстер должен быть собой."),
    tags: ["spicy", "signature"],
    featured: false,
    seasonal: false,
    chefChoice: false,
    emphasis: "md",
    alt: L("Lobster linguine with tomato and chili", "Лингвини с лобстером"),
  }),
  dish({
    id: "cacio-e-pepe",
    slug: "cacio-e-pepe",
    name: L("Cacio e Pepe", "Cacio e pepe"),
    category: "pasta",
    summary: L("Tonarelli · pecorino · black pepper", "Тонарелли · пекорино · чёрный перец"),
    description: L(
      "Three ingredients, no shortcuts. Emulsion, heat, pepper cracked at the end.",
      "Три ингредиента, без сокращений. Эмульсия, жар, перец в финале.",
    ),
    price: "1 190 ₽",
    image: I.cacio,
    gallery: gallery(I.cacio, I.pasta, I.kitchen),
    ingredients: [
      ing("tonarelli", "Tonarelli", "Тонарелли", I.cacio, "110 г"),
      ing("pecorino", "Pecorino", "Пекорино", I.burrata, "40 г"),
      ing("pepper", "Black pepper", "Чёрный перец", I.cacio, "3 г"),
    ],
    allergens: [L("Gluten", "Глютен"), L("Milk", "Молоко")],
    pairing: { name: L("Frascati", "Фраскати"), price: "790 ₽ / glass" },
    chefNote: L("If it looks creamy, you waited.", "Если выглядит как крем — вы подождали."),
    tags: ["vegetarian"],
    featured: false,
    seasonal: false,
    chefChoice: false,
    emphasis: "sm",
    alt: L("Cacio e pepe with pecorino and black pepper", "Cacio e pepe"),
  }),
  dish({
    id: "duck-breast",
    slug: "duck-breast",
    name: L("Duck Breast", "Утиная грудка"),
    category: "mains",
    summary: L("Duck · cherry · celery root", "Утка · вишня · сельдерей"),
    description: L(
      "Rendered skin, pink centre, cherry that is more acid than sweet.",
      "Вытопленный жир, розовый центр, вишня скорее кислая, чем сладкая.",
    ),
    price: "2 190 ₽",
    image: I.duck,
    gallery: gallery(I.duck, I.steak, I.kitchen, I.chef),
    ingredients: [
      ing("duck", "Duck", "Утка", I.duck, "180 г"),
      ing("cherry", "Cherry", "Вишня", I.dessert, "40 г"),
      ing("celery", "Celery root", "Корень сельдерея", I.veg, "70 г"),
    ],
    allergens: [],
    pairing: { name: L("Barolo", "Бароло"), price: "1 600 ₽ / glass" },
    chefNote: L("Rest the bird. Serve it when it has decided.", "Дайте птице отдохнуть."),
    tags: ["chefs-choice", "seasonal"],
    featured: false,
    seasonal: true,
    chefChoice: true,
    emphasis: "xl",
    alt: L("Duck breast with cherry and celery root", "Утиная грудка"),
  }),
  dish({
    id: "beef-tenderloin",
    slug: "beef-tenderloin",
    name: L("Beef Tenderloin", "Говяжья вырезка"),
    category: "mains",
    summary: L("Beef · pepper jus · potato", "Говядина · перечный соус · картофель"),
    description: L(
      "A quiet cut, a darker jus, potato cooked in butter until it almost disappears.",
      "Тихий отруб, тёмный соус, картофель на масле, пока почти не исчезнет.",
    ),
    price: "2 490 ₽",
    image: I.steak,
    gallery: gallery(I.steak, I.tartare, I.kitchen, I.room),
    ingredients: [
      ing("beef", "Beef", "Говядина", I.steak, "200 г"),
      ing("pepper", "Pepper jus", "Перечный соус", I.steak, "50 мл"),
      ing("potato", "Potato", "Картофель", I.fries, "120 г"),
    ],
    allergens: [L("Milk", "Молоко")],
    pairing: { name: L("Cabernet Franc", "Каберне фран"), price: "1 350 ₽ / glass" },
    chefNote: L("Salt early. Heat late.", "Соль рано. Жар поздно."),
    tags: ["signature"],
    featured: false,
    seasonal: false,
    chefChoice: false,
    emphasis: "lg",
    alt: L("Beef tenderloin with pepper jus", "Говяжья вырезка"),
  }),
  dish({
    id: "chicken-supreme",
    slug: "chicken-supreme",
    name: L("Chicken Supreme", "Куриный суприм"),
    category: "mains",
    summary: L("Chicken · morel · cream", "Курица · сморчок · сливки"),
    description: L(
      "A precise supreme, morels in a short cream, nothing rustic about it.",
      "Точный суприм, сморчки в коротких сливках — без деревенского жеста.",
    ),
    price: "1 690 ₽",
    image: I.chicken,
    gallery: gallery(I.chicken, I.kitchen, I.chef),
    ingredients: [
      ing("chicken", "Chicken", "Курица", I.chicken, "180 г"),
      ing("morel", "Morel", "Сморчок", I.truffle, "30 г"),
      ing("cream", "Cream", "Сливки", I.dessert, "40 мл"),
    ],
    allergens: [L("Milk", "Молоко")],
    pairing: { name: L("Meursault", "Мерсо"), price: "1 550 ₽ / glass" },
    chefNote: L("Treat chicken as if it were expensive. It is.", "Готовьте курицу так, будто она дорогая. Так и есть."),
    tags: ["chefs-choice"],
    featured: false,
    seasonal: false,
    chefChoice: true,
    emphasis: "md",
    alt: L("Chicken supreme with morel cream", "Куриный суприм"),
  }),
  dish({
    id: "seared-scallops",
    slug: "seared-scallops",
    name: L("Seared Scallops", "Морские гребешки"),
    category: "seafood",
    summary: L("Scallop · cauliflower · beurre blanc", "Гребешок · цветная капуста · beurre blanc"),
    description: L(
      "A hard sear, a quiet purée, butter that holds lemon without shouting.",
      "Жёсткий sear, тихий крем, масло держит лимон без крика.",
    ),
    price: "1 890 ₽",
    image: I.scallops,
    gallery: gallery(I.scallops, I.octopus, I.kitchen),
    ingredients: [
      ing("scallop", "Scallop", "Гребешок", I.scallops, "140 г"),
      ing("cauliflower", "Cauliflower", "Цветная капуста", I.veg, "80 г"),
      ing("butter", "Beurre blanc", "Beurre blanc", I.dessert, "35 мл"),
    ],
    allergens: [L("Mollusc", "Моллюски"), L("Milk", "Молоко")],
    pairing: { name: L("Chablis Premier Cru", "Шабли Premier Cru"), price: "1 480 ₽ / glass" },
    chefNote: L("One side only. Leave the centre translucent.", "Только одна сторона. Центр — полупрозрачный."),
    tags: ["chefs-choice", "signature"],
    featured: false,
    seasonal: false,
    chefChoice: true,
    emphasis: "lg",
    alt: L("Seared scallops with cauliflower and beurre blanc", "Морские гребешки"),
  }),
  dish({
    id: "sea-bass",
    slug: "sea-bass",
    name: L("Sea Bass", "Сибас"),
    category: "seafood",
    summary: L("Sea bass · fennel · lemon", "Сибас · фенхель · лимон"),
    description: L(
      "Crisp skin, fennel cooked until sweet, lemon as structure.",
      "Хрустящая кожа, фенхель до сладости, лимон как каркас.",
    ),
    price: "2 090 ₽",
    image: I.seabass,
    gallery: gallery(I.seabass, I.salmon, I.kitchen),
    ingredients: [
      ing("bass", "Sea bass", "Сибас", I.seabass, "220 г"),
      ing("fennel", "Fennel", "Фенхель", I.veg, "60 г"),
      ing("lemon", "Lemon", "Лимон", I.lemon, "15 г"),
    ],
    allergens: [L("Fish", "Рыба")],
    pairing: { name: L("Assyrtiko", "Ассиртико"), price: "920 ₽ / glass" },
    chefNote: L("The skin is the seasoning.", "Кожа — это приправа."),
    tags: ["seasonal"],
    featured: false,
    seasonal: true,
    chefChoice: false,
    emphasis: "md",
    alt: L("Sea bass with fennel and lemon", "Сибас с фенхелем"),
  }),
  dish({
    id: "truffle-fries",
    slug: "truffle-fries",
    name: L("Truffle Fries", "Картофель с трюфелем"),
    category: "sides",
    summary: L("Potato · truffle · parmesan", "Картофель · трюфель · пармезан"),
    description: L(
      "Twice-cooked, finished with oil and a restrained grate of cheese.",
      "Двойная готовка, масло и сдержанная стружка сыра.",
    ),
    price: "790 ₽",
    image: I.fries,
    gallery: gallery(I.fries, I.truffle),
    ingredients: [
      ing("potato", "Potato", "Картофель", I.fries, "180 г"),
      ing("truffle", "Truffle", "Трюфель", I.truffle, "6 г"),
      ing("parmesan", "Parmesan", "Пармезан", I.burrata, "15 г"),
    ],
    allergens: [L("Milk", "Молоко")],
    pairing: { name: L("House sparkling", "Игристое дома"), price: "690 ₽ / glass" },
    chefNote: L("Crisp first. Perfume second.", "Сначала хруст. Потом аромат."),
    tags: ["vegetarian", "signature"],
    featured: false,
    seasonal: false,
    chefChoice: false,
    emphasis: "sm",
    alt: L("Truffle fries on dark ceramic", "Картофель с трюфелем"),
  }),
  dish({
    id: "roasted-vegetables",
    slug: "roasted-vegetables",
    name: L("Roasted Vegetables", "Печёные овощи"),
    category: "sides",
    summary: L("Seasonal roots · herbs · oil", "Сезонные корнеплоды · травы · масло"),
    description: L(
      "High heat, little moisture, herbs added after the oven.",
      "Высокий жар, мало влаги, травы — после печи.",
    ),
    price: "590 ₽",
    image: I.veg,
    gallery: gallery(I.veg, I.salad),
    ingredients: [
      ing("roots", "Seasonal roots", "Сезонные корнеплоды", I.veg, "220 г"),
      ing("herbs", "Herbs", "Травы", I.salad, "8 г"),
      ing("oil", "Olive oil", "Оливковое масло", I.veg, "15 мл"),
    ],
    allergens: [],
    pairing: { name: L("Natural white", "Натуральное белое"), price: "850 ₽ / glass" },
    chefNote: L("Colour is doneness.", "Цвет — это готовность."),
    tags: ["vegetarian", "seasonal"],
    featured: false,
    seasonal: true,
    chefChoice: false,
    emphasis: "md",
    alt: L("Roasted seasonal vegetables", "Печёные овощи"),
  }),
  dish({
    id: "green-salad",
    slug: "green-salad",
    name: L("Green Salad", "Зелёный салат"),
    category: "sides",
    summary: L("Leaves · lemon · oil", "Листья · лимон · масло"),
    description: L(
      "Bitter greens, a sharp lemon, oil that does not coat.",
      "Горькая зелень, острый лимон, масло, которое не обволакивает.",
    ),
    price: "490 ₽",
    image: I.salad,
    gallery: gallery(I.salad, I.veg),
    ingredients: [
      ing("leaves", "Leaves", "Листья", I.salad, "90 г"),
      ing("lemon", "Lemon", "Лимон", I.lemon, "20 г"),
      ing("oil", "Oil", "Масло", I.salad, "12 мл"),
    ],
    allergens: [],
    pairing: { name: L("Still water, citrus", "Вода с цитрусом"), price: "—" },
    chefNote: L("Dress in the bowl you serve.", "Заправляйте в той же посуде, в которой подаёте."),
    tags: ["vegetarian"],
    featured: false,
    seasonal: false,
    chefChoice: false,
    emphasis: "sm",
    alt: L("Green salad with lemon and oil", "Зелёный салат"),
  }),
  dish({
    id: "noire-chocolate",
    slug: "noire-chocolate",
    name: L("NOIRÉ Chocolate", "Шоколад NOIRÉ"),
    category: "desserts",
    summary: L("Dark chocolate · vanilla · salt", "Тёмный шоколад · ваниль · соль"),
    description: L(
      "Dark chocolate, a cold cream, salt that arrives last — the evening’s quiet closing note.",
      "Тёмный шоколад, холодный крем, соль в финале — тихая закрывающая нота вечера.",
    ),
    price: "790 ₽",
    image: I.dessert,
    gallery: gallery(I.dessert, I.fig, I.kitchen, I.room),
    ingredients: [
      ing("chocolate", "Dark chocolate", "Тёмный шоколад", I.dessert, "70 г"),
      ing("vanilla", "Vanilla", "Ваниль", I.dessert, "8 г"),
      ing("salt", "Salt", "Соль", I.dessert, "1 г"),
    ],
    allergens: [L("Milk", "Молоко")],
    pairing: { name: L("Pedro Ximénez", "Педро Хименес"), price: "890 ₽ / glass" },
    chefNote: L("Serve colder than you think.", "Подавайте холоднее, чем кажется."),
    tags: ["signature", "vegetarian"],
    featured: true,
    seasonal: false,
    chefChoice: false,
    emphasis: "lg",
    alt: L("Dark chocolate dessert with vanilla and salt", "Шоколад NOIRÉ"),
  }),
  dish({
    id: "fig-caramel",
    slug: "fig-caramel",
    name: L("Fig & Caramel", "Инжир и карамель"),
    category: "desserts",
    summary: L("Fig · caramel · mascarpone", "Инжир · карамель · маскарпоне"),
    description: L(
      "Roasted fig, dark caramel, mascarpone that stays unsweetened.",
      "Печёный инжир, тёмная карамель, маскарпоне без сладости.",
    ),
    price: "750 ₽",
    image: I.fig,
    gallery: gallery(I.fig, I.dessert, I.bar),
    ingredients: [
      ing("fig", "Fig", "Инжир", I.fig, "90 г"),
      ing("caramel", "Caramel", "Карамель", I.dessert, "30 г"),
      ing("mascarpone", "Mascarpone", "Маскарпоне", I.burrata, "40 г"),
    ],
    allergens: [L("Milk", "Молоко")],
    pairing: { name: L("Vin santo", "Vin santo"), price: "820 ₽ / glass" },
    chefNote: L("The fig should still taste of the tree.", "Инжир должен оставаться инжиром."),
    tags: ["vegetarian", "seasonal"],
    featured: false,
    seasonal: true,
    chefChoice: false,
    emphasis: "md",
    alt: L("Fig and caramel dessert with mascarpone", "Инжир и карамель"),
  }),
  dish({
    id: "lemon-cloud",
    slug: "lemon-cloud",
    name: L("Lemon Cloud", "Лимонное облако"),
    category: "desserts",
    summary: L("Lemon · meringue · cream", "Лимон · меренга · крем"),
    description: L(
      "A light set cream, sharp lemon, meringue that barely holds.",
      "Лёгкий крем, острый лимон, меренга, которая едва держит форму.",
    ),
    price: "690 ₽",
    image: I.lemon,
    gallery: gallery(I.lemon, I.dessert),
    ingredients: [
      ing("lemon", "Lemon", "Лимон", I.lemon, "45 г"),
      ing("meringue", "Meringue", "Меренга", I.lemon, "20 г"),
      ing("cream", "Cream", "Крем", I.dessert, "50 г"),
    ],
    allergens: [L("Egg", "Яйцо"), L("Milk", "Молоко")],
    pairing: { name: L("Moscato d’Asti", "Москато д’Асти"), price: "690 ₽ / glass" },
    chefNote: L("Acid is the structure.", "Кислота — это каркас."),
    tags: ["vegetarian"],
    featured: false,
    seasonal: false,
    chefChoice: false,
    emphasis: "sm",
    alt: L("Lemon cloud with meringue and cream", "Лимонное облако"),
  }),
  dish({
    id: "noir-martini",
    slug: "noir-martini",
    name: L("Noir Martini", "Noir Martini"),
    category: "drinks",
    summary: L("Vodka · olive · vermouth", "Водка · оливка · вермут"),
    description: L(
      "Vodka, a dry vermouth, olive brine, a single twist of lemon oil.",
      "Водка, сухой вермут, рассол оливы, одно касание лимонного масла.",
    ),
    price: "890 ₽",
    image: I.cocktail,
    gallery: gallery(I.cocktail, I.bar, I.room),
    ingredients: [
      ing("vodka", "Vodka", "Водка", I.cocktail, "50 мл"),
      ing("olive", "Olive", "Оливка", I.cocktail, "8 г"),
      ing("vermouth", "Vermouth", "Вермут", I.bar, "10 мл"),
    ],
    allergens: [],
    pairing: { name: L("Oysters, if in season", "Устрицы, если сезон"), price: "—" },
    chefNote: L("Stir. Never shake the house martini.", "Размешивать. Домашний мартини не шейкают."),
    tags: ["signature"],
    featured: false,
    seasonal: false,
    chefChoice: false,
    emphasis: "md",
    alt: L("Noir Martini with olive", "Noir Martini"),
  }),
  dish({
    id: "midnight-fig",
    slug: "midnight-fig",
    name: L("Midnight Fig", "Midnight Fig"),
    category: "drinks",
    summary: L("Fig · gin · citrus", "Инжир · джин · цитрус"),
    description: L(
      "Roasted fig, gin, a bitter citrus edge for the later hour.",
      "Печёный инжир, джин, горький цитрус для позднего часа.",
    ),
    price: "990 ₽",
    image: I.bar,
    gallery: gallery(I.bar, I.fig, I.cocktail),
    ingredients: [
      ing("fig", "Fig", "Инжир", I.fig, "25 г"),
      ing("gin", "Gin", "Джин", I.bar, "45 мл"),
      ing("citrus", "Citrus", "Цитрус", I.lemon, "20 мл"),
    ],
    allergens: [],
    pairing: { name: L("After the mains", "После горячего"), price: "—" },
    chefNote: L("Built for the room, not for a list.", "Для этого зала, не для карты."),
    tags: ["seasonal", "signature"],
    featured: false,
    seasonal: true,
    chefChoice: false,
    emphasis: "lg",
    alt: L("Midnight Fig cocktail", "Midnight Fig"),
  }),
  dish({
    id: "smoked-negroni",
    slug: "smoked-negroni",
    name: L("Smoked Negroni", "Smoked Negroni"),
    category: "drinks",
    summary: L("Gin · vermouth · bitter orange", "Джин · вермут · горький апельсин"),
    description: L(
      "Campari, sweet vermouth, gin, orange peel smoked in glass.",
      "Кампари, сладкий вермут, джин, копчёная в бокале цедра.",
    ),
    price: "950 ₽",
    image: I.cocktail,
    gallery: gallery(I.cocktail, I.bar),
    ingredients: [
      ing("gin", "Gin", "Джин", I.bar, "30 мл"),
      ing("vermouth", "Vermouth", "Вермут", I.cocktail, "30 мл"),
      ing("orange", "Bitter orange", "Горький апельсин", I.lemon, "30 мл"),
    ],
    allergens: [],
    pairing: { name: L("Dark chocolate", "Тёмный шоколад"), price: "—" },
    chefNote: L("Smoke the glass, not the drink.", "Коптить бокал, не напиток."),
    tags: ["signature"],
    featured: false,
    seasonal: false,
    chefChoice: false,
    emphasis: "sm",
    alt: L("Smoked Negroni with orange peel", "Smoked Negroni"),
  }),
];

export const cocktails: Cocktail[] = dishes
  .filter((item) => item.category === "drinks")
  .map((item) => ({
    name: item.name.en,
    price: item.price,
    image: item.image,
    notes: item.summary,
  }));

export function getDish(slug: string): Dish | undefined {
  return dishes.find((item) => item.slug === slug);
}

export function getCategoryLabel(id: CategoryId, locale: "en" | "ru") {
  return menuCategories.find((item) => item.id === id)?.label[locale] ?? id;
}

export function relatedDishes(dish: Dish, count = 3): Dish[] {
  const same = dishes.filter(
    (item) => item.slug !== dish.slug && item.category === dish.category,
  );
  const rest = dishes.filter(
    (item) => item.slug !== dish.slug && item.category !== dish.category,
  );
  return [...same, ...rest].slice(0, count);
}

export function searchDishes(query: string, locale: "en" | "ru"): Dish[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return dishes.filter((dish) => {
    const hay = [
      dish.name[locale],
      dish.name.en,
      dish.summary[locale],
      dish.description[locale],
      getCategoryLabel(dish.category, locale),
      ...dish.ingredients.map((item) => item.name[locale]),
      ...dish.tags,
    ]
      .join(" ")
      .toLowerCase();
    return hay.includes(q);
  });
}

export function dishMatchesTags(dish: Dish, tags: DishTag[]): boolean {
  if (tags.length === 0) return true;
  return tags.every((tag) => {
    if (tag === "chefs-choice") return dish.chefChoice || dish.tags.includes(tag);
    if (tag === "seasonal") return dish.seasonal || dish.tags.includes(tag);
    return dish.tags.includes(tag);
  });
}

export const featuredDishes = dishes.filter((dish) => dish.featured);
export const seasonalDishes = dishes.filter((dish) => dish.seasonal);
export const autumnCollection = [
  "black-truffle-tagliolini",
  "duck-breast",
  "fig-caramel",
]
  .map((slug) => dishes.find((dish) => dish.slug === slug))
  .filter((dish): dish is Dish => Boolean(dish));
